# -*- coding: utf-8 -*-
# @Time   : 2026/9/5
# @Author : Junze Yang / revised with ChatGPT
# @File   : graph_metric.py

"""OD-aware criticality metrics for the directed road network.

Required upstream files
-----------------------
    node.csv
    link.csv
    res/od/od_connector.csv       <- generated by od_prepare.py

Node and directed-link metrics (same four dimensions for both)
---------------------------------------------------------------
1. ``odbc``
   OD-weighted shortest-path load centrality (betweenness-style). Connector OD
   demand is assigned to distance-shortest directed paths. Road nodes on the
   selected path, including road access endpoints, receive the OD demand. For
   parallel minimum-length links, demand is divided equally among tied links.

2. ``od_eff_loss``
   Relative loss of demand-weighted network efficiency after isolated removal:

       E_OD = sum(q_rs / d_rs) / sum(q_rs)
       loss = (E0 - E_removed) / E0

   Baseline-unreachable connector OD is excluded consistently from all
   demand-based metrics. Newly unreachable OD contributes zero to E_OD.

3. ``lscc_loss``
   Relative loss of the largest strongly connected component (LSCC) share.
   This remains deliberately topological and is not OD weighted.

4. ``td_loss``
   Demand-weighted total-distance loss after isolated removal. To keep this
   metric finite when an OD becomes disconnected, a newly unreachable OD is
   assigned a transparent, data-derived disruption penalty:

       disrupted distance = baseline distance + D_penalty
       D_penalty = maximum finite baseline connector-OD distance

   The script also reports ``unreachable_demand_share`` as a diagnostic so the
   penalty is never hidden.

All route costs are ``length_m`` only. No free-flow speed, capacity, BPR, or UE
assignment is used.

Outputs
-------
    res/graph_metric/node_metric.csv
    res/graph_metric/link_metric.csv
    res/graph_metric/summary.csv
    res/graph_metric/metric_meta.json
    res/graph_metric/cache/od_active.csv
    res/graph_metric/cache/node_index.csv

Examples
--------
    python code/graph_metric.py
    python code/graph_metric.py --workers 6
    python code/graph_metric.py --no-parallel
    python code/graph_metric.py --test-components 30
"""

from __future__ import annotations

import os
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import argparse
import json
import math
import multiprocessing as mp
import sys
import time
import warnings
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components, dijkstra

try:
    from tqdm import tqdm
except Exception:
    tqdm = None


# =============================================================================
# Paths / settings
# =============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]
NODE_PATH = PROJECT_ROOT / "node.csv"
LINK_PATH = PROJECT_ROOT / "link.csv"
OD_PATH = PROJECT_ROOT / "res" / "od" / "od_connector.csv"
OD_META_PATH = PROJECT_ROOT / "res" / "od" / "od_meta.json"

RESULT_DIR = PROJECT_ROOT / "res" / "graph_metric"
CACHE_DIR = RESULT_DIR / "cache"
NODE_OUT = RESULT_DIR / "node_metric.csv"
LINK_OUT = RESULT_DIR / "link_metric.csv"
SUMMARY_OUT = RESULT_DIR / "summary.csv"
META_OUT = RESULT_DIR / "metric_meta.json"
OD_ACTIVE_OUT = CACHE_DIR / "od_active.csv"
NODE_INDEX_OUT = CACHE_DIR / "node_index.csv"

DEFAULT_WORKERS = max(1, min((os.cpu_count() or 2) - 1, 8))
DEFAULT_PARALLEL = True
MASTER_SEED = 20260905
EPS = 1e-12
PRED_NULL = -9999

_W: Dict[str, Any] = {}


# =============================================================================
# I/O helpers
# =============================================================================

def read_csv_auto(path: Path) -> Tuple[pd.DataFrame, str]:
    errors = []
    for enc in ("utf-8-sig", "utf-8", "gb18030", "gbk"):
        try:
            return pd.read_csv(path, encoding=enc), enc
        except UnicodeDecodeError as exc:
            errors.append("%s: %s" % (enc, exc))
    raise UnicodeError("Cannot decode %s. %s" % (path, errors))


def require_columns(df: pd.DataFrame, cols: Iterable[str], name: str) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError("%s is missing required columns: %s" % (name, missing))


def add_rank_columns(df: pd.DataFrame, value_col: str, prefix: str) -> None:
    s = pd.to_numeric(df[value_col], errors="coerce")
    df[prefix + "_rank"] = s.rank(
        method="min", ascending=False, na_option="bottom"
    ).astype(int)
    # Larger raw value -> larger percentile; maximum = 1.
    df[prefix + "_pct"] = s.rank(method="average", pct=True)


# =============================================================================
# Directed MultiDiGraph represented as minimum-weight ordered pairs
# =============================================================================

def prepare_network(nodes: pd.DataFrame, links: pd.DataFrame) -> Dict[str, Any]:
    node_ids = np.asarray(
        sorted(pd.to_numeric(nodes["node_id"], errors="raise").astype(np.int64)),
        dtype=np.int64,
    )
    n = len(node_ids)
    node_to_idx = {int(x): i for i, x in enumerate(node_ids)}

    work = links[["link_id", "from_node", "to_node", "length_m"]].copy()
    work["link_id"] = pd.to_numeric(work["link_id"], errors="raise").astype(np.int64)
    work["from_node"] = pd.to_numeric(work["from_node"], errors="raise").astype(np.int64)
    work["to_node"] = pd.to_numeric(work["to_node"], errors="raise").astype(np.int64)
    work["length_m"] = pd.to_numeric(work["length_m"], errors="raise").astype(float)
    if work["link_id"].duplicated().any():
        raise ValueError("link.csv contains duplicate link_id values.")
    if np.any(~np.isfinite(work["length_m"])) or np.any(work["length_m"] <= 0):
        raise ValueError("All length_m values must be finite and positive.")

    work["u_idx"] = work["from_node"].map(node_to_idx)
    work["v_idx"] = work["to_node"].map(node_to_idx)
    if work[["u_idx", "v_idx"]].isna().any().any():
        raise ValueError("link.csv references node IDs absent from node.csv.")
    work["u_idx"] = work["u_idx"].astype(np.int32)
    work["v_idx"] = work["v_idx"].astype(np.int32)
    work["_pos"] = np.arange(len(work), dtype=np.int32)

    link_ids = work["link_id"].to_numpy(dtype=np.int64)
    link_lengths = work["length_m"].to_numpy(dtype=np.float64)
    link_id_to_pos = {int(x): i for i, x in enumerate(link_ids)}

    pair_rows: List[int] = []
    pair_cols: List[int] = []
    pair_link_positions: List[np.ndarray] = []
    pair_lookup: Dict[Tuple[int, int], int] = {}

    for p, ((u, v), grp) in enumerate(work.groupby(["u_idx", "v_idx"], sort=True)):
        grp = grp.sort_values(["length_m", "link_id"])
        pair_rows.append(int(u))
        pair_cols.append(int(v))
        positions = grp["_pos"].to_numpy(dtype=np.int32)
        pair_link_positions.append(positions)
        pair_lookup[(int(u), int(v))] = int(p)

    pair_rows_arr = np.asarray(pair_rows, dtype=np.int32)
    pair_cols_arr = np.asarray(pair_cols, dtype=np.int32)
    base_weights = np.asarray(
        [link_lengths[int(pos[0])] for pos in pair_link_positions],
        dtype=np.float64,
    )
    base_adj = csr_matrix(
        (base_weights, (pair_rows_arr, pair_cols_arr)),
        shape=(n, n),
        dtype=np.float64,
    )

    return {
        "n": int(n),
        "node_ids": node_ids,
        "node_to_idx": node_to_idx,
        "link_ids": link_ids,
        "link_lengths": link_lengths,
        "link_id_to_pos": link_id_to_pos,
        "pair_rows": pair_rows_arr,
        "pair_cols": pair_cols_arr,
        "pair_link_positions": tuple(pair_link_positions),
        "pair_lookup": pair_lookup,
        "base_weights": base_weights,
        "base_adj": base_adj,
        "n_links": int(len(link_ids)),
    }


def lscc_share(adj: csr_matrix, n_total: int) -> float:
    if n_total <= 0:
        return 0.0
    n_comp, labels = connected_components(
        adj, directed=True, connection="strong", return_labels=True
    )
    if labels.size == 0:
        return 0.0
    counts = np.bincount(labels, minlength=n_comp)
    return float(counts.max() / n_total)


# =============================================================================
# OD demand preparation and baseline shortest paths
# =============================================================================

def prepare_od(od: pd.DataFrame, network: Dict[str, Any]) -> pd.DataFrame:
    require_columns(od, ["origin_node", "destination_node", "demand"], "od_connector.csv")
    out = od[["origin_node", "destination_node", "demand"]].copy()
    out["origin_node"] = pd.to_numeric(out["origin_node"], errors="raise").astype(np.int64)
    out["destination_node"] = pd.to_numeric(out["destination_node"], errors="raise").astype(np.int64)
    out["demand"] = pd.to_numeric(out["demand"], errors="coerce").astype(float)
    out = out[np.isfinite(out["demand"]) & (out["demand"] > 0)].copy()
    out = out[out["origin_node"] != out["destination_node"]].copy()

    valid_nodes = set(int(x) for x in network["node_ids"])
    bad = (~out["origin_node"].isin(valid_nodes)) | (~out["destination_node"].isin(valid_nodes))
    if bad.any():
        raise ValueError("OD connector table references road nodes absent from node.csv.")

    # Aggregate identical road-node pairs to reduce repeated extraction work.
    out = (
        out.groupby(["origin_node", "destination_node"], as_index=False)["demand"]
        .sum()
        .sort_values(["origin_node", "destination_node"])
        .reset_index(drop=True)
    )
    out["origin_idx"] = out["origin_node"].map(network["node_to_idx"]).astype(np.int32)
    out["destination_idx"] = out["destination_node"].map(network["node_to_idx"]).astype(np.int32)
    return out


def baseline_od_shortest_paths(
    od: pd.DataFrame,
    network: Dict[str, Any],
) -> Tuple[pd.DataFrame, np.ndarray, np.ndarray, np.ndarray, Dict[int, int]]:
    sources = np.sort(od["origin_idx"].unique().astype(np.int32))
    source_row = {int(s): i for i, s in enumerate(sources)}
    print("Computing baseline OD-source directed shortest paths (%d sources)..." % len(sources))
    dist, pred = dijkstra(
        network["base_adj"],
        directed=True,
        indices=sources,
        return_predecessors=True,
    )
    if dist.ndim == 1:
        dist = dist.reshape(1, -1)
        pred = pred.reshape(1, -1)

    rows = np.asarray([source_row[int(x)] for x in od["origin_idx"]], dtype=np.int32)
    dst = od["destination_idx"].to_numpy(dtype=np.int32)
    d0 = dist[rows, dst]
    active = np.isfinite(d0) & (d0 > 0)

    out = od.loc[active].copy().reset_index(drop=True)
    out["baseline_distance_m"] = d0[active].astype(float)
    out.insert(0, "active_od_id", np.arange(len(out), dtype=np.int64))
    if out.empty:
        raise RuntimeError("No connector OD pair is reachable on the directed road network.")

    return out, sources, dist, pred, source_row


def reconstruct_path(pred_row: np.ndarray, source: int, target: int) -> Optional[List[int]]:
    if source == target:
        return [int(source)]
    path = [int(target)]
    cur = int(target)
    seen = {cur}
    max_steps = len(pred_row) + 2
    for _ in range(max_steps):
        p = int(pred_row[cur])
        if p == PRED_NULL or p < 0:
            return None
        path.append(p)
        if p == source:
            path.reverse()
            return path
        if p in seen:
            return None
        seen.add(p)
        cur = p
    return None


def compute_odbc(
    active_od: pd.DataFrame,
    pred: np.ndarray,
    source_row: Dict[int, int],
    network: Dict[str, Any],
) -> Tuple[np.ndarray, np.ndarray, Dict[str, float]]:
    node_load = np.zeros(network["n"], dtype=np.float64)
    link_load = np.zeros(network["n_links"], dtype=np.float64)
    total_q = float(active_od["demand"].to_numpy(dtype=np.float64).sum(dtype=np.float64))
    failures = 0

    link_lengths = network["link_lengths"]
    link_ids = network["link_ids"]

    iterator = active_od.itertuples(index=False)
    if tqdm is not None:
        iterator = tqdm(iterator, total=len(active_od), desc="OD path loading", unit="OD")

    for row in iterator:
        s = int(row.origin_idx)
        t = int(row.destination_idx)
        q = float(row.demand)
        prow = pred[source_row[s]]
        path = reconstruct_path(prow, s, t)
        if path is None or len(path) < 2:
            failures += 1
            continue

        # Connector road nodes are real road-network access locations. They are
        # included in load centrality because zone endpoints themselves are not
        # graph nodes; this avoids artificially assigning zero importance to an
        # access node whose removal affects its represented demand.
        node_load[np.asarray(path, dtype=np.int32)] += q

        for u, v in zip(path[:-1], path[1:]):
            p = network["pair_lookup"].get((int(u), int(v)))
            if p is None:
                failures += 1
                continue
            positions = network["pair_link_positions"][int(p)]
            min_len = float(link_lengths[int(positions[0])])
            tied = [
                int(pos)
                for pos in positions
                if abs(float(link_lengths[int(pos)]) - min_len) <= 1e-9
            ]
            share = q / max(1, len(tied))
            for pos in tied:
                link_load[pos] += share

    if failures:
        warnings.warn("%d path-loading predecessor/edge inconsistencies detected." % failures)

    if total_q > 0:
        node_odbc = node_load / total_q
        link_odbc = link_load / total_q
    else:
        node_odbc = node_load
        link_odbc = link_load

    stats = {
        "active_demand": total_q,
        "node_load_sum": float(node_load.sum(dtype=np.float64)),
        "link_load_sum": float(link_load.sum(dtype=np.float64)),
        "path_loading_failures": int(failures),
    }
    return node_odbc, link_odbc, stats


# =============================================================================
# Demand metrics for a network state
# =============================================================================

def od_state_metrics_from_distances(
    distances: np.ndarray,
    active_od: pd.DataFrame,
    source_row: Dict[int, int],
    baseline_total_distance: float,
    disconnect_penalty_m: float,
) -> Dict[str, float]:
    src_rows = np.asarray(
        [source_row[int(x)] for x in active_od["origin_idx"]], dtype=np.int32
    )
    dst = active_od["destination_idx"].to_numpy(dtype=np.int32)
    q = active_od["demand"].to_numpy(dtype=np.float64)
    d0 = active_od["baseline_distance_m"].to_numpy(dtype=np.float64)
    ds = distances[src_rows, dst]

    reachable = np.isfinite(ds) & (ds > 0)
    q_total = float(q.sum(dtype=np.float64))
    q_reach = float(q[reachable].sum(dtype=np.float64))

    efficiency = (
        float(np.sum(q[reachable] / ds[reachable], dtype=np.float64) / q_total)
        if q_total > 0
        else 0.0
    )

    penalized = np.where(reachable, ds, d0 + float(disconnect_penalty_m))
    total_distance = float(np.sum(q * penalized, dtype=np.float64))
    td_loss = (
        (total_distance - baseline_total_distance) / baseline_total_distance
        if baseline_total_distance > 0
        else float("nan")
    )
    if abs(td_loss) < 1e-12:
        td_loss = 0.0

    return {
        "od_eff": efficiency,
        "penalized_total_distance": total_distance,
        "td_loss": float(td_loss),
        "reachable_demand_share": float(q_reach / q_total) if q_total > 0 else np.nan,
    }


# =============================================================================
# Worker state
# =============================================================================

def init_worker(
    n: int,
    pair_rows: np.ndarray,
    pair_cols: np.ndarray,
    pair_link_positions: Tuple[np.ndarray, ...],
    base_weights: np.ndarray,
    link_ids: np.ndarray,
    link_lengths: np.ndarray,
    node_ids: np.ndarray,
    sources: np.ndarray,
    od_origin_idx: np.ndarray,
    od_destination_idx: np.ndarray,
    od_demand: np.ndarray,
    od_baseline_distance: np.ndarray,
    base_eff: float,
    base_total_distance: float,
    disconnect_penalty_m: float,
    base_lscc: float,
) -> None:
    global _W
    _W = {
        "n": int(n),
        "pair_rows": np.asarray(pair_rows, dtype=np.int32),
        "pair_cols": np.asarray(pair_cols, dtype=np.int32),
        "pair_link_positions": tuple(np.asarray(x, dtype=np.int32) for x in pair_link_positions),
        "base_weights": np.asarray(base_weights, dtype=np.float64),
        "link_ids": np.asarray(link_ids, dtype=np.int64),
        "link_lengths": np.asarray(link_lengths, dtype=np.float64),
        "link_id_to_pos": {int(x): i for i, x in enumerate(link_ids)},
        "node_ids": np.asarray(node_ids, dtype=np.int64),
        "node_id_to_idx": {int(x): i for i, x in enumerate(node_ids)},
        "sources": np.asarray(sources, dtype=np.int32),
        "source_row": {int(x): i for i, x in enumerate(sources)},
        "od_origin_idx": np.asarray(od_origin_idx, dtype=np.int32),
        "od_destination_idx": np.asarray(od_destination_idx, dtype=np.int32),
        "od_demand": np.asarray(od_demand, dtype=np.float64),
        "od_baseline_distance": np.asarray(od_baseline_distance, dtype=np.float64),
        "base_eff": float(base_eff),
        "base_total_distance": float(base_total_distance),
        "disconnect_penalty_m": float(disconnect_penalty_m),
        "base_lscc": float(base_lscc),
        "n_links": int(len(link_ids)),
    }


def adjacency_after_one_link(link_id: int) -> csr_matrix:
    pos_remove = _W["link_id_to_pos"][int(link_id)]
    rows = _W["pair_rows"]
    cols = _W["pair_cols"]
    groups = _W["pair_link_positions"]
    lengths = _W["link_lengths"]

    weights = np.empty(len(groups), dtype=np.float64)
    keep = np.zeros(len(groups), dtype=bool)
    for p, positions in enumerate(groups):
        chosen = -1
        for pos in positions:
            if int(pos) != int(pos_remove):
                chosen = int(pos)
                break
        if chosen >= 0:
            weights[p] = lengths[chosen]
            keep[p] = True
    return csr_matrix(
        (weights[keep], (rows[keep], cols[keep])),
        shape=(_W["n"], _W["n"]),
        dtype=np.float64,
    )


def adjacency_after_one_node(node_id: int) -> csr_matrix:
    idx = _W["node_id_to_idx"][int(node_id)]
    rows = _W["pair_rows"]
    cols = _W["pair_cols"]
    keep = (rows != idx) & (cols != idx)
    return csr_matrix(
        (_W["base_weights"][keep], (rows[keep], cols[keep])),
        shape=(_W["n"], _W["n"]),
        dtype=np.float64,
    )


def worker_state_metrics(adj: csr_matrix, demand_affected: bool) -> Tuple[float, float, float, float]:
    scc = lscc_share(adj, _W["n"])
    lscc_loss = (
        (_W["base_lscc"] - scc) / _W["base_lscc"]
        if _W["base_lscc"] > 0
        else np.nan
    )
    if abs(lscc_loss) < 1e-12:
        lscc_loss = 0.0

    if not demand_affected:
        return 0.0, float(lscc_loss), 0.0, 1.0

    dist = dijkstra(
        adj, directed=True, indices=_W["sources"], return_predecessors=False
    )
    if dist.ndim == 1:
        dist = dist.reshape(1, -1)

    src_rows = np.asarray(
        [_W["source_row"][int(x)] for x in _W["od_origin_idx"]], dtype=np.int32
    )
    dst = _W["od_destination_idx"]
    q = _W["od_demand"]
    d0 = _W["od_baseline_distance"]
    ds = dist[src_rows, dst]
    reachable = np.isfinite(ds) & (ds > 0)
    q_total = float(q.sum(dtype=np.float64))
    q_reach = float(q[reachable].sum(dtype=np.float64))

    eff = (
        float(np.sum(q[reachable] / ds[reachable], dtype=np.float64) / q_total)
        if q_total > 0
        else 0.0
    )
    eff_loss = (
        (_W["base_eff"] - eff) / _W["base_eff"]
        if _W["base_eff"] > 0
        else np.nan
    )
    if abs(eff_loss) < 1e-12:
        eff_loss = 0.0

    penalized = np.where(reachable, ds, d0 + _W["disconnect_penalty_m"])
    total_distance = float(np.sum(q * penalized, dtype=np.float64))
    td_loss = (
        (total_distance - _W["base_total_distance"]) / _W["base_total_distance"]
        if _W["base_total_distance"] > 0
        else np.nan
    )
    if abs(td_loss) < 1e-12:
        td_loss = 0.0

    reach_share = float(q_reach / q_total) if q_total > 0 else np.nan
    return float(eff_loss), float(lscc_loss), float(td_loss), reach_share


def eval_link_chunk(tasks: Sequence[Tuple[int, bool]]) -> List[Tuple[int, float, float, float, float]]:
    rows = []
    for link_id, affected in tasks:
        adj = adjacency_after_one_link(int(link_id))
        e, s, td, r = worker_state_metrics(adj, bool(affected))
        rows.append((int(link_id), e, s, td, r))
    return rows


def eval_node_chunk(tasks: Sequence[Tuple[int, bool]]) -> List[Tuple[int, float, float, float, float]]:
    rows = []
    for node_id, affected in tasks:
        adj = adjacency_after_one_node(int(node_id))
        e, s, td, r = worker_state_metrics(adj, bool(affected))
        rows.append((int(node_id), e, s, td, r))
    return rows


def chunks(values: Sequence[Any], n_chunks_hint: int) -> List[List[Any]]:
    vals = list(values)
    if not vals:
        return []
    n_chunks_hint = max(1, min(int(n_chunks_hint), len(vals)))
    size = int(math.ceil(len(vals) / n_chunks_hint))
    return [vals[i : i + size] for i in range(0, len(vals), size)]


def evaluate_components(
    component: str,
    tasks: Sequence[Tuple[int, bool]],
    parallel: bool,
    workers: int,
    initargs: Tuple[Any, ...],
) -> List[Tuple[int, float, float, float, float]]:
    fn = eval_link_chunk if component == "link" else eval_node_chunk
    task_chunks = chunks(tasks, workers * 8 if parallel else 1)
    if not parallel or workers <= 1:
        init_worker(*initargs)
        rows = []
        iterator = task_chunks
        if tqdm is not None:
            iterator = tqdm(iterator, desc=component + " removals", unit="chunk")
        for chunk in iterator:
            rows.extend(fn(chunk))
        return rows

    rows = []
    with ProcessPoolExecutor(
        max_workers=workers, initializer=init_worker, initargs=initargs
    ) as ex:
        futures = [ex.submit(fn, chunk) for chunk in task_chunks]
        iterator = as_completed(futures)
        if tqdm is not None:
            iterator = tqdm(
                iterator, total=len(futures), desc=component + " removals", unit="chunk"
            )
        for fut in iterator:
            rows.extend(fut.result())
    return rows


# =============================================================================
# Summary / CLI
# =============================================================================

def build_summary(node_result: pd.DataFrame, link_result: pd.DataFrame, baseline: Dict[str, float]) -> pd.DataFrame:
    rows: List[Dict[str, Any]] = []

    def add(entity: str, metric: str, s: pd.Series) -> None:
        x = pd.to_numeric(s, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
        if x.empty:
            return
        for stat, val in [
            ("min", x.min()),
            ("median", x.median()),
            ("p90", x.quantile(0.90)),
            ("p95", x.quantile(0.95)),
            ("max", x.max()),
        ]:
            rows.append({"entity": entity, "metric": metric, "stat": stat, "value": float(val)})

    for metric in ("odbc", "od_eff_loss", "lscc_loss", "td_loss"):
        add("node", metric, node_result[metric])
        add("link", metric, link_result[metric])
    for k, v in baseline.items():
        if isinstance(v, (int, float, np.integer, np.floating)):
            rows.append({"entity": "network", "metric": k, "stat": "value", "value": float(v)})
    return pd.DataFrame(rows)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--parallel", dest="parallel", action="store_true")
    group.add_argument("--no-parallel", dest="parallel", action="store_false")
    parser.set_defaults(parallel=DEFAULT_PARALLEL)
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS)
    parser.add_argument(
        "--test-components",
        type=int,
        default=0,
        help="evaluate first N links/nodes only; 0 = all",
    )
    return parser.parse_args()


# =============================================================================
# Main
# =============================================================================

def main() -> int:
    args = parse_args()
    started = time.perf_counter()
    workers = max(1, int(args.workers))
    parallel = bool(args.parallel and workers > 1)

    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    required = [NODE_PATH, LINK_PATH, OD_PATH]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing inputs: %s. Run net.py (if needed) and od_prepare.py first." % missing
        )

    nodes, node_enc = read_csv_auto(NODE_PATH)
    links, link_enc = read_csv_auto(LINK_PATH)
    od_raw, od_enc = read_csv_auto(OD_PATH)
    require_columns(nodes, ["node_id", "lon", "lat"], "node.csv")
    require_columns(links, ["link_id", "from_node", "to_node", "length_m"], "link.csv")

    nodes = nodes.copy()
    links = links.copy()
    nodes["node_id"] = pd.to_numeric(nodes["node_id"], errors="raise").astype(np.int64)
    links["link_id"] = pd.to_numeric(links["link_id"], errors="raise").astype(np.int64)
    links["from_node"] = pd.to_numeric(links["from_node"], errors="raise").astype(np.int64)
    links["to_node"] = pd.to_numeric(links["to_node"], errors="raise").astype(np.int64)
    links["length_m"] = pd.to_numeric(links["length_m"], errors="raise").astype(float)

    network = prepare_network(nodes, links)
    od = prepare_od(od_raw, network)
    print("Loaded %d nodes, %d directed links, %d aggregated connector OD pairs." % (
        len(nodes), len(links), len(od)
    ))

    node_index = pd.DataFrame({
        "index": np.arange(network["n"], dtype=np.int32),
        "node_id": network["node_ids"],
    })
    node_index.to_csv(NODE_INDEX_OUT, index=False, encoding="utf-8-sig")

    active_od, sources, dist0, pred0, source_row = baseline_od_shortest_paths(od, network)
    raw_q = float(od["demand"].to_numpy(dtype=np.float64).sum(dtype=np.float64))
    active_q = float(active_od["demand"].to_numpy(dtype=np.float64).sum(dtype=np.float64))
    active_od[[
        "active_od_id", "origin_node", "destination_node", "origin_idx",
        "destination_idx", "demand", "baseline_distance_m"
    ]].to_csv(OD_ACTIVE_OUT, index=False, encoding="utf-8-sig")

    q = active_od["demand"].to_numpy(dtype=np.float64)
    d0 = active_od["baseline_distance_m"].to_numpy(dtype=np.float64)
    base_eff = float(np.sum(q / d0, dtype=np.float64) / q.sum(dtype=np.float64))
    base_total_distance = float(np.sum(q * d0, dtype=np.float64))
    disconnect_penalty_m = float(np.max(d0))
    base_lscc = lscc_share(network["base_adj"], network["n"])

    node_odbc, link_odbc, load_stats = compute_odbc(
        active_od, pred0, source_row, network
    )

    node_odbc_map = {
        int(network["node_ids"][i]): float(node_odbc[i])
        for i in range(network["n"])
    }
    link_odbc_map = {
        int(network["link_ids"][i]): float(link_odbc[i])
        for i in range(network["n_links"])
    }

    initargs = (
        network["n"],
        network["pair_rows"],
        network["pair_cols"],
        network["pair_link_positions"],
        network["base_weights"],
        network["link_ids"],
        network["link_lengths"],
        network["node_ids"],
        sources,
        active_od["origin_idx"].to_numpy(dtype=np.int32),
        active_od["destination_idx"].to_numpy(dtype=np.int32),
        active_od["demand"].to_numpy(dtype=np.float64),
        active_od["baseline_distance_m"].to_numpy(dtype=np.float64),
        base_eff,
        base_total_distance,
        disconnect_penalty_m,
        base_lscc,
    )

    link_ids = [int(x) for x in network["link_ids"]]
    node_ids = [int(x) for x in network["node_ids"]]
    if int(args.test_components) > 0:
        k = int(args.test_components)
        warnings.warn("TEST MODE: evaluating first %d links and first %d nodes." % (k, k))
        link_ids = link_ids[:k]
        node_ids = node_ids[:k]

    # A positive-length shortest path can only worsen after removing a component
    # that lies on at least one selected baseline shortest path. Components with
    # zero ODBC therefore skip repeated OD Dijkstra while still receiving exact
    # LSCC loss. This is exact for the selected deterministic shortest paths;
    # equal-length parallel links already share ODBC and are recomputed.
    link_tasks = [(lid, link_odbc_map.get(lid, 0.0) > 0.0) for lid in link_ids]
    node_tasks = [(nid, node_odbc_map.get(nid, 0.0) > 0.0) for nid in node_ids]

    print(
        "Evaluating isolated removals: parallel=%s, workers=%d, OD-active links=%d/%d, nodes=%d/%d"
        % (
            parallel,
            workers if parallel else 1,
            sum(a for _, a in link_tasks), len(link_tasks),
            sum(a for _, a in node_tasks), len(node_tasks),
        )
    )
    t_rem = time.perf_counter()
    link_eval = evaluate_components("link", link_tasks, parallel, workers, initargs)
    node_eval = evaluate_components("node", node_tasks, parallel, workers, initargs)
    removal_seconds = time.perf_counter() - t_rem

    # Assemble node results.
    node_keep = [c for c in ["node_id", "osm_id", "lon", "lat"] if c in nodes.columns]
    node_result = nodes[node_keep].copy()
    node_result["odbc"] = node_result["node_id"].map(node_odbc_map).fillna(0.0).astype(float)
    node_eval_df = pd.DataFrame(
        node_eval,
        columns=["node_id", "od_eff_loss", "lscc_loss", "td_loss", "reachable_demand_share"],
    )
    node_result = node_result.merge(node_eval_df, on="node_id", how="left")

    # Assemble link results.
    keep_cols = [c for c in (
        "link_id", "from_node", "to_node", "u_osm", "v_osm", "edge_key",
        "osm_way", "name", "highway", "oneway", "length_m", "lanes",
        "maxspeed", "ref", "access", "bridge", "tunnel", "geometry"
    ) if c in links.columns]
    link_result = links[keep_cols].copy()
    link_result["odbc"] = link_result["link_id"].map(link_odbc_map).fillna(0.0).astype(float)
    link_eval_df = pd.DataFrame(
        link_eval,
        columns=["link_id", "od_eff_loss", "lscc_loss", "td_loss", "reachable_demand_share"],
    )
    link_result = link_result.merge(link_eval_df, on="link_id", how="left")

    # In test mode, unevaluated components stay NaN except ODBC. In full mode,
    # every component must have all isolated-removal metrics.
    if int(args.test_components) <= 0:
        req = ["od_eff_loss", "lscc_loss", "td_loss", "reachable_demand_share"]
        if node_result[req].isna().any().any() or link_result[req].isna().any().any():
            raise RuntimeError("Missing isolated-removal metric in full run.")

    for df in (node_result, link_result):
        for col in ("od_eff_loss", "lscc_loss", "td_loss"):
            bad = df[col] < -1e-8
            if bad.fillna(False).any():
                warnings.warn("Negative %s values detected; inspect numerical/data consistency." % col)
            tiny = df[col].abs() < 1e-12
            df.loc[tiny.fillna(False), col] = 0.0
        add_rank_columns(df, "odbc", "odbc")
        add_rank_columns(df, "od_eff_loss", "od_eff")
        add_rank_columns(df, "lscc_loss", "lscc")
        add_rank_columns(df, "td_loss", "td")

    node_result.to_csv(NODE_OUT, index=False, encoding="utf-8-sig")
    link_result.to_csv(LINK_OUT, index=False, encoding="utf-8-sig")

    baseline = {
        "n_nodes": int(network["n"]),
        "n_directed_links": int(network["n_links"]),
        "raw_connector_demand": raw_q,
        "active_connector_demand": active_q,
        "baseline_reachable_demand_share": active_q / raw_q if raw_q > 0 else np.nan,
        "od_efficiency": base_eff,
        "lscc_share": base_lscc,
        "total_distance_m_trip": base_total_distance,
        "disconnect_penalty_m": disconnect_penalty_m,
        "active_od_pairs": int(len(active_od)),
        "od_source_nodes": int(len(sources)),
    }
    build_summary(node_result, link_result, baseline).to_csv(
        SUMMARY_OUT, index=False, encoding="utf-8-sig"
    )

    runtime = time.perf_counter() - started
    meta = {
        "input": {
            "node_csv": str(NODE_PATH),
            "link_csv": str(LINK_PATH),
            "od_connector_csv": str(OD_PATH),
            "node_encoding": node_enc,
            "link_encoding": link_enc,
            "od_encoding": od_enc,
        },
        "graph": {
            "nodes": int(network["n"]),
            "directed_links": int(network["n_links"]),
            "unique_ordered_node_pairs": int(len(network["pair_rows"])),
            "weight": "length_m",
            "directed": True,
            "parallel_links": True,
        },
        "metrics": {
            "common_node_link_metrics": [
                "odbc", "od_eff_loss", "lscc_loss", "td_loss"
            ],
            "odbc": (
                "OD-weighted distance-shortest-path load / total active OD demand; "
                "road access endpoint nodes included; tied minimum parallel links split equally"
            ),
            "od_eff_loss": (
                "relative loss of sum(q/d)/sum(q) after isolated removal"
            ),
            "lscc_loss": "relative loss of largest strongly connected component share",
            "td_loss": (
                "relative increase of demand-weighted total distance; newly unreachable "
                "OD assigned baseline distance + max baseline OD distance"
            ),
            "unreachable_diagnostic": "reachable_demand_share is saved for every isolated removal",
        },
        "baseline": baseline,
        "od_path_loading": load_stats,
        "runtime_seconds": {
            "isolated_removals": float(removal_seconds),
            "total": float(runtime),
        },
        "parallel": {"enabled": parallel, "workers": workers if parallel else 1},
        "outputs": {
            "node_metric": str(NODE_OUT),
            "link_metric": str(LINK_OUT),
            "summary": str(SUMMARY_OUT),
            "active_od": str(OD_ACTIVE_OUT),
            "node_index": str(NODE_INDEX_OUT),
        },
        "test_components": int(args.test_components),
        "seed": MASTER_SEED,
    }
    META_OUT.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")

    print("\nCompleted OD-aware graph metrics.")
    print(f"  Baseline active OD demand: {active_q:,.2f} ({100.0 * baseline['baseline_reachable_demand_share']:.2f}% of mapped road-proxy demand)")
    print("  OD efficiency: %.10g 1/m" % base_eff)
    print("  LSCC share: %.6f" % base_lscc)
    print(f"  Total weighted distance: {base_total_distance:,.3f} m-trip")
    print("  Disconnection penalty: %.1f m" % disconnect_penalty_m)
    print("  Runtime: %.1f s" % runtime)
    print("  Saved: %s" % RESULT_DIR)
    return 0


if __name__ == "__main__":
    mp.freeze_support()
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("Interrupted by user.", file=sys.stderr)
        raise SystemExit(130)
